---
language: bash

jobs:
  include:
    - os: linux
      dist: bionic
      before_install:
        - freebsd-version
      name: Ubuntu 18 bionic + Zabbix 4.4
      arch: amd64
      addons:
        apt:
          sources:
            - sourceline: 'deb http://repo.zabbix.com/zabbix/4.4/ubuntu bionic main'
              key_url: "https://repo.zabbix.com/zabbix-official-repo.key"
          packages:
            - grep
            - gawk
            - lsof
            - jq
            - libfcgi-bin
            - unzip
            - zabbix-agent
            - zabbix-get
      before_script:
        - sudo curl -o /usr/local/bin/shunit2 https://raw.githubusercontent.com/kward/shunit2/master/shunit2

script: bash tests/all.sh
notifications:
  email: false
