---
language: bash

jobs:
  include:
    - os: linux
      dist: bionic
      name: "Zabbix 4.4 @ Ubuntu 18 bionic, PHP default"
      arch: amd64
      addons:
        apt:
          sources:
            - sourceline: 'deb http://repo.zabbix.com/zabbix/4.4/ubuntu bionic main'
              key_url: "https://repo.zabbix.com/zabbix-official-repo.key"
            - sourceline: 'ppa:ondrej/php'
          packages:
            - apt-transport-https
            - ca-certificates
            - curl
            - grep
            - sed
            - gawk
            - lsof
            - jq
            - libfcgi-bin
            - unzip
            - zabbix-agent
            - zabbix-get
            - php-fpm
      before_script:
        - sudo curl -o /usr/local/bin/shunit2 https://raw.githubusercontent.com/kward/shunit2/master/shunit2

script: bash tests/all.sh
notifications:
  email: false
env:
  - SH=bash
